services:
  db:
    image: docker.io/library/mysql:8.4
    container_name: demo_mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: pword
      MYSQL_ROOT_PASSWORD: pwordR

    volumes:
      - mysqldata:/var/lib/mysql
    # Descomenta si necesitas acceso externo a MySQL
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=pword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - conectionService

  app:
    build:
      context: ./Backend/sysmarket
      dockerfile: Dockerfile
    container_name: demo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://demo_mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      db_username: appuser
      db_password: 
    ports:
      - "8080:8080"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # Distroless ya corre como non-root (uid 65532). Si usas otra imagen, añade USER no-root.
    networks:
      - conectionService
volumes:  
  mysqldata:
#
networks:
  conectionService:
    driver: bridge
#